/* Generated by tools/figma/tokens.mjs from src/styles/tokens.css. Do not edit. */
const TOKENS = {
  "modes": [
    "Desktop",
    "Tablet",
    "Mobile"
  ],
  "colours": {
    "blue": "#a3c6d7",
    "purple": "#ac91e1",
    "grey": "#d7d7d7",
    "grey-dark": "#444444",
    "amber": "#ffd05a",
    "white": "#ffffff",
    "ink": "#000000",
    "ink-2": "#1a1a1a"
  },
  "sizes": {
    "hero": {
      "Desktop": 76,
      "Tablet": 58,
      "Mobile": 42
    },
    "h1": {
      "Desktop": 64,
      "Tablet": 48,
      "Mobile": 36
    },
    "h2": {
      "Desktop": 48,
      "Tablet": 38,
      "Mobile": 30
    },
    "h2-journey": {
      "Desktop": 44,
      "Tablet": 36,
      "Mobile": 32
    },
    "eyebrow": {
      "Desktop": 34,
      "Tablet": 27,
      "Mobile": 22
    },
    "h3": {
      "Desktop": 30,
      "Tablet": 24,
      "Mobile": 20
    },
    "card-title": {
      "Desktop": 26,
      "Tablet": 26,
      "Mobile": 22
    },
    "track-title": {
      "Desktop": 24,
      "Tablet": 24,
      "Mobile": 24
    },
    "stat": {
      "Desktop": 62,
      "Tablet": 52,
      "Mobile": 46
    },
    "stat-2": {
      "Desktop": 52,
      "Tablet": 44,
      "Mobile": 38
    },
    "body-size": {
      "Desktop": 15,
      "Tablet": 15,
      "Mobile": 15
    },
    "small": {
      "Desktop": 13,
      "Tablet": 13,
      "Mobile": 13
    },
    "micro": {
      "Desktop": 11,
      "Tablet": 11,
      "Mobile": 11
    },
    "mono-size": {
      "Desktop": 13,
      "Tablet": 13,
      "Mobile": 13
    }
  },
  "radii": {
    "r-pill": {
      "Desktop": 999,
      "Tablet": 999,
      "Mobile": 999
    },
    "r-band": {
      "Desktop": 24,
      "Tablet": 24,
      "Mobile": 24
    },
    "r-card": {
      "Desktop": 20,
      "Tablet": 20,
      "Mobile": 20
    },
    "r-tile": {
      "Desktop": 16,
      "Tablet": 16,
      "Mobile": 16
    },
    "r-editorial": {
      "Desktop": 12,
      "Tablet": 12,
      "Mobile": 12
    }
  },
  "space": {
    "frame": {
      "Desktop": 1440,
      "Tablet": 1440,
      "Mobile": 1440
    },
    "gutter": {
      "Desktop": 64,
      "Tablet": 40,
      "Mobile": 22
    },
    "section": {
      "Desktop": 96,
      "Tablet": 96,
      "Mobile": 64
    }
  },
  "text": [
    {
      "name": "Display/Hero",
      "size": "hero",
      "family": "display",
      "weight": 300,
      "lh": "lh-hero"
    },
    {
      "name": "Display/H1",
      "size": "h1",
      "family": "display",
      "weight": 300,
      "lh": 1.05
    },
    {
      "name": "Display/H2",
      "size": "h2",
      "family": "display",
      "weight": 300,
      "lh": 1.1
    },
    {
      "name": "Display/H3",
      "size": "h3",
      "family": "display",
      "weight": 300,
      "lh": 1.15
    },
    {
      "name": "Display/Eyebrow",
      "size": "eyebrow",
      "family": "display",
      "weight": 300,
      "lh": "lh-eyebrow"
    },
    {
      "name": "Display/Card title",
      "size": "card-title",
      "family": "display",
      "weight": 400,
      "lh": 1.2
    },
    {
      "name": "Display/Stat",
      "size": "stat",
      "family": "display",
      "weight": 300,
      "lh": 1
    },
    {
      "name": "Body/Regular",
      "size": "body-size",
      "family": "body",
      "weight": 400,
      "lh": 1.6
    },
    {
      "name": "Body/Small",
      "size": "small",
      "family": "body",
      "weight": 400,
      "lh": 1.5
    },
    {
      "name": "Mono/Label",
      "size": "mono-size",
      "family": "mono",
      "weight": 400,
      "lh": 1.4,
      "tracking": 0.08
    },
    {
      "name": "Mono/Micro",
      "size": "micro",
      "family": "mono",
      "weight": 400,
      "lh": 1.4,
      "tracking": 0.08
    }
  ],
  "families": {
    "display": {
      "family": "Poppins",
      "styles": {
        "300": "Light",
        "400": "Regular"
      }
    },
    "body": {
      "family": "Anybody",
      "styles": {
        "300": "Light",
        "348": "Regular",
        "400": "Regular"
      }
    },
    "mono": {
      "family": "IBM Plex Mono",
      "styles": {
        "400": "Regular",
        "500": "Medium"
      }
    },
    "arabic": {
      "family": "IBM Plex Sans Arabic",
      "styles": {
        "400": "Regular"
      }
    }
  },
  "bodyVariation": "'wdth' 117, 'wght' 348"
}
