import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const c = await b.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 })
const p = await c.newPage()
p.on('console', m => { if (m.type()==='error') console.log('ERR', m.text().slice(0,120)) })
await p.goto('http://localhost:4180/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2000)
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
await p.waitForTimeout(2500)
await p.evaluate(() => window.scrollTo(0, 0))
await p.waitForTimeout(3500)
await p.screenshot({ path: '/home/claude/younit-web/tools/shots/REF-home.png', fullPage: true })
await b.close()
console.log('ref shot taken')
