/* Built by tools/figma/build-plugin.mjs — edit figma-plugin/src/*.js instead. */

/* ===== 00-tokens.js ===== */
/* Generated by tools/figma/tokens.mjs from src/styles/tokens.css. Do not edit. */
const TOKENS = {
  "modes": [
    "Desktop",
    "Tablet",
    "Mobile"
  ],
  "colours": {
    "blue": "#a3c6d7",
    "purple": "#ac91e1",
    "grey": "#d7d7d7",
    "grey-dark": "#444444",
    "amber": "#ffd05a",
    "white": "#ffffff",
    "ink": "#000000",
    "ink-2": "#1a1a1a"
  },
  "sizes": {
    "hero": {
      "Desktop": 76,
      "Tablet": 58,
      "Mobile": 42
    },
    "h1": {
      "Desktop": 64,
      "Tablet": 48,
      "Mobile": 36
    },
    "h2": {
      "Desktop": 48,
      "Tablet": 38,
      "Mobile": 30
    },
    "h2-journey": {
      "Desktop": 44,
      "Tablet": 36,
      "Mobile": 32
    },
    "eyebrow": {
      "Desktop": 34,
      "Tablet": 27,
      "Mobile": 22
    },
    "h3": {
      "Desktop": 30,
      "Tablet": 24,
      "Mobile": 20
    },
    "card-title": {
      "Desktop": 26,
      "Tablet": 26,
      "Mobile": 22
    },
    "track-title": {
      "Desktop": 24,
      "Tablet": 24,
      "Mobile": 24
    },
    "stat": {
      "Desktop": 62,
      "Tablet": 52,
      "Mobile": 46
    },
    "stat-2": {
      "Desktop": 52,
      "Tablet": 44,
      "Mobile": 38
    },
    "body-size": {
      "Desktop": 15,
      "Tablet": 15,
      "Mobile": 15
    },
    "small": {
      "Desktop": 13,
      "Tablet": 13,
      "Mobile": 13
    },
    "micro": {
      "Desktop": 11,
      "Tablet": 11,
      "Mobile": 11
    },
    "mono-size": {
      "Desktop": 13,
      "Tablet": 13,
      "Mobile": 13
    }
  },
  "radii": {
    "r-pill": {
      "Desktop": 999,
      "Tablet": 999,
      "Mobile": 999
    },
    "r-band": {
      "Desktop": 24,
      "Tablet": 24,
      "Mobile": 24
    },
    "r-card": {
      "Desktop": 20,
      "Tablet": 20,
      "Mobile": 20
    },
    "r-tile": {
      "Desktop": 16,
      "Tablet": 16,
      "Mobile": 16
    },
    "r-editorial": {
      "Desktop": 12,
      "Tablet": 12,
      "Mobile": 12
    }
  },
  "space": {
    "frame": {
      "Desktop": 1440,
      "Tablet": 1440,
      "Mobile": 1440
    },
    "gutter": {
      "Desktop": 64,
      "Tablet": 40,
      "Mobile": 22
    },
    "section": {
      "Desktop": 96,
      "Tablet": 96,
      "Mobile": 64
    }
  },
  "text": [
    {
      "name": "Display/Hero",
      "size": "hero",
      "family": "display",
      "weight": 300,
      "lh": "lh-hero"
    },
    {
      "name": "Display/H1",
      "size": "h1",
      "family": "display",
      "weight": 300,
      "lh": 1.05
    },
    {
      "name": "Display/H2",
      "size": "h2",
      "family": "display",
      "weight": 300,
      "lh": 1.1
    },
    {
      "name": "Display/H3",
      "size": "h3",
      "family": "display",
      "weight": 300,
      "lh": 1.15
    },
    {
      "name": "Display/Eyebrow",
      "size": "eyebrow",
      "family": "display",
      "weight": 300,
      "lh": "lh-eyebrow"
    },
    {
      "name": "Display/Card title",
      "size": "card-title",
      "family": "display",
      "weight": 400,
      "lh": 1.2
    },
    {
      "name": "Display/Stat",
      "size": "stat",
      "family": "display",
      "weight": 300,
      "lh": 1
    },
    {
      "name": "Body/Regular",
      "size": "body-size",
      "family": "body",
      "weight": 400,
      "lh": 1.6
    },
    {
      "name": "Body/Small",
      "size": "small",
      "family": "body",
      "weight": 400,
      "lh": 1.5
    },
    {
      "name": "Mono/Label",
      "size": "mono-size",
      "family": "mono",
      "weight": 400,
      "lh": 1.4,
      "tracking": 0.08
    },
    {
      "name": "Mono/Micro",
      "size": "micro",
      "family": "mono",
      "weight": 400,
      "lh": 1.4,
      "tracking": 0.08
    }
  ],
  "families": {
    "display": {
      "family": "Poppins",
      "styles": {
        "300": "Light",
        "400": "Regular"
      }
    },
    "body": {
      "family": "Anybody",
      "styles": {
        "300": "Light",
        "348": "Regular",
        "400": "Regular"
      }
    },
    "mono": {
      "family": "IBM Plex Mono",
      "styles": {
        "400": "Regular",
        "500": "Medium"
      }
    },
    "arabic": {
      "family": "IBM Plex Sans Arabic",
      "styles": {
        "400": "Regular"
      }
    }
  },
  "bodyVariation": "'wdth' 117, 'wght' 348"
}


/* ===== 10-util.js ===== */
/* --------------------------------------------------------------------------
   Small shared things: colour, fonts, and talking to the panel.
   -------------------------------------------------------------------------- */

/** Where the snapshots are published. The panel can point this somewhere else. */
let BASE = 'https://younit-gray.vercel.app'

const say = (message) => figma.ui.postMessage({ kind: 'log', message })
const step = (done, total, label) =>
  figma.ui.postMessage({ kind: 'progress', done, total, label })

/** `#a3c6d7` → Figma's 0–1 triple. */
function hex(value) {
  const s = value.replace('#', '')
  const full = s.length === 3 ? s.split('').map((c) => c + c).join('') : s
  return {
    r: parseInt(full.slice(0, 2), 16) / 255,
    g: parseInt(full.slice(2, 4), 16) / 255,
    b: parseInt(full.slice(4, 6), 16) / 255,
  }
}

const solid = (rgb, opacity) => ({
  type: 'SOLID',
  color: { r: rgb.r, g: rgb.g, b: rgb.b },
  opacity: opacity === undefined ? 1 : opacity,
})

/**
 * The site's palette, indexed by the colour Figma would compute, so a fill
 * measured off the page can be recognised as a token rather than pasted as a
 * loose hex. This is what keeps the imported pages tied to the design system:
 * change `--yn-blue` in Figma later and every card that used it follows.
 */
const PALETTE = []
for (const name of Object.keys(TOKENS.colours)) {
  PALETTE.push({ name, rgb: hex(TOKENS.colours[name]) })
}

const near = (a, b) => Math.abs(a - b) < 0.012

function tokenFor(rgb) {
  for (const entry of PALETTE) {
    if (near(entry.rgb.r, rgb.r) && near(entry.rgb.g, rgb.g) && near(entry.rgb.b, rgb.b)) {
      return entry.name
    }
  }
  return null
}

/* --- Fonts ----------------------------------------------------------------

   Anybody is a variable font pinned to `wdth 117, wght 348` on the site.
   Figma reaches a variable font through its named instances, and the instance
   names differ between the static and variable releases, so each family is
   given a list of candidates and the first one the file has is the one used.
   If none load the family is reported once, by name, rather than failing the
   import halfway through.
   -------------------------------------------------------------------------- */

const FONT_CANDIDATES = {
  Poppins: {
    300: ['Light'],
    400: ['Regular'],
    500: ['Medium'],
    600: ['SemiBold'],
    700: ['Bold'],
  },
  Anybody: {
    300: ['SemiExpanded Light', 'Light', 'Regular'],
    348: ['SemiExpanded Light', 'SemiExpanded Regular', 'Light', 'Regular'],
    400: ['SemiExpanded Regular', 'Regular'],
    500: ['SemiExpanded Medium', 'Medium', 'Regular'],
    600: ['SemiExpanded SemiBold', 'SemiBold', 'Regular'],
    700: ['SemiExpanded Bold', 'Bold', 'Regular'],
  },
  'IBM Plex Mono': { 400: ['Regular'], 500: ['Medium'], 600: ['SemiBold'], 700: ['Bold'] },
  'IBM Plex Sans Arabic': { 300: ['Light'], 400: ['Regular'], 500: ['Medium'], 700: ['Bold'] },
}

const FALLBACK = { family: 'Inter', style: 'Regular' }
const loaded = {}
const missing = {}

async function font(family, weight) {
  const key = family + '/' + weight
  if (loaded[key]) return loaded[key]

  const table = FONT_CANDIDATES[family] || {}
  const names = table[weight] || table[400] || ['Regular']
  for (const style of names) {
    try {
      await figma.loadFontAsync({ family: family, style: style })
      loaded[key] = { family: family, style: style }
      return loaded[key]
    } catch (e) {
      /* try the next name */
    }
  }

  if (!missing[family]) {
    missing[family] = true
    say('Missing font: ' + family + ' — install it and run again for correct type.')
  }
  await figma.loadFontAsync(FALLBACK)
  loaded[key] = FALLBACK
  return FALLBACK
}

/** Which of the four families a measured font-family string belongs to. */
function familyOf(name) {
  const n = (name || '').toLowerCase()
  if (n.indexOf('poppins') === 0) return 'Poppins'
  if (n.indexOf('anybody') === 0) return 'Anybody'
  if (n.indexOf('ibm plex mono') === 0) return 'IBM Plex Mono'
  if (n.indexOf('ibm plex sans arabic') === 0) return 'IBM Plex Sans Arabic'
  return 'Anybody'
}


/* ===== 20-system.js ===== */
/* --------------------------------------------------------------------------
   The design system: variables first, then the styles that read them, then the
   components built out of both.

   Order matters. A text style bound to a size variable follows the mode, so
   switching a frame from Desktop to Mobile resizes every heading inside it —
   but only if the variable exists before the style is made. Same for the
   components: a button whose fill is bound to `colour/white` updates when the
   palette does, and a button painted with a loose hex never will.
   -------------------------------------------------------------------------- */

/** Collections are reused across runs so a second import does not duplicate them. */
async function collection(name, modes) {
  const existing = await figma.variables.getLocalVariableCollectionsAsync()
  for (const c of existing) {
    if (c.name === name) return c
  }

  const made = figma.variables.createVariableCollection(name)
  made.renameMode(made.modes[0].modeId, modes[0])
  for (let i = 1; i < modes.length; i++) made.addMode(modes[i])
  return made
}

async function variable(collection, name, type) {
  const existing = await figma.variables.getLocalVariablesAsync()
  for (const v of existing) {
    if (v.name === name && v.variableCollectionId === collection.id) return v
  }
  return figma.variables.createVariable(name, collection, type)
}

const VARS = { colour: {}, size: {}, radius: {}, space: {} }

async function buildVariables() {
  say('Variables…')

  // Colour does not change with the width of the screen, so it gets a
  // collection of its own rather than three identical modes.
  const paint = await collection('Younit / Colour', ['Value'])
  const paintMode = paint.modes[0].modeId
  for (const name of Object.keys(TOKENS.colours)) {
    const v = await variable(paint, name, 'COLOR')
    v.setValueForMode(paintMode, hex(TOKENS.colours[name]))
    VARS.colour[name] = v
  }

  // Everything measured in pixels does change, and the stylesheet already says
  // how: three media queries, three modes, one variable each.
  const scale = await collection('Younit / Scale', TOKENS.modes)
  const modeIds = {}
  for (const mode of scale.modes) modeIds[mode.name] = mode.modeId

  const groups = [
    ['type/', TOKENS.sizes, VARS.size],
    ['radius/', TOKENS.radii, VARS.radius],
    ['space/', TOKENS.space, VARS.space],
  ]

  for (const group of groups) {
    const prefix = group[0]
    const source = group[1]
    const store = group[2]
    for (const name of Object.keys(source)) {
      const v = await variable(scale, prefix + name, 'FLOAT')
      for (const modeName of Object.keys(source[name])) {
        if (modeIds[modeName] !== undefined) v.setValueForMode(modeIds[modeName], source[name][modeName])
      }
      store[name] = v
    }
  }

  say(
    Object.keys(VARS.colour).length +
      ' colours, ' +
      Object.keys(VARS.size).length +
      ' type sizes x ' +
      TOKENS.modes.length +
      ' modes, ' +
      Object.keys(VARS.radius).length +
      ' radii, ' +
      Object.keys(VARS.space).length +
      ' spacing',
  )
}

async function buildPaintStyles() {
  const existing = await figma.getLocalPaintStylesAsync()
  const byName = {}
  for (const s of existing) byName[s.name] = s

  for (const name of Object.keys(TOKENS.colours)) {
    const styleName = 'Younit/' + name
    const style = byName[styleName] || figma.createPaintStyle()
    style.name = styleName
    const fill = solid(hex(TOKENS.colours[name]))
    style.paints = [
      VARS.colour[name]
        ? figma.variables.setBoundVariableForPaint(fill, 'color', VARS.colour[name])
        : fill,
    ]
  }
  say(Object.keys(TOKENS.colours).length + ' paint styles')
}

async function buildTextStyles() {
  const existing = await figma.getLocalTextStylesAsync()
  const byName = {}
  for (const s of existing) byName[s.name] = s

  for (const spec of TOKENS.text) {
    const family = TOKENS.families[spec.family].family
    const chosen = await font(family, spec.weight)
    const style = byName['Younit/' + spec.name] || figma.createTextStyle()
    style.name = 'Younit/' + spec.name
    style.fontName = chosen
    style.fontSize = TOKENS.sizes[spec.size] ? TOKENS.sizes[spec.size].Desktop : 16

    const lh = typeof spec.lh === 'number' ? spec.lh : 1.15
    style.lineHeight = { unit: 'PERCENT', value: Math.round(lh * 100) }
    if (spec.tracking) style.letterSpacing = { unit: 'PERCENT', value: spec.tracking * 100 }

    // The binding is the point: the number above is only what Desktop shows.
    if (VARS.size[spec.size]) {
      try {
        style.setBoundVariable('fontSize', VARS.size[spec.size])
      } catch (e) {
        /* older editors cannot bind a style; the value above still stands */
      }
    }
  }
  say(TOKENS.text.length + ' text styles')
}

/* --- Components -----------------------------------------------------------

   Built rather than traced. These are the pieces the site repeats, and a
   traced copy of one of them is a picture of a button; a component is a button.
   Everything here paints from the variables above.
   -------------------------------------------------------------------------- */

function bindFill(node, token, opacity) {
  const fill = solid(hex(TOKENS.colours[token]), opacity)
  node.fills = [
    VARS.colour[token] ? figma.variables.setBoundVariableForPaint(fill, 'color', VARS.colour[token]) : fill,
  ]
}

function bindStroke(node, token, weight) {
  const fill = solid(hex(TOKENS.colours[token]))
  node.strokes = [
    VARS.colour[token] ? figma.variables.setBoundVariableForPaint(fill, 'color', VARS.colour[token]) : fill,
  ]
  node.strokeWeight = weight === undefined ? 1 : weight
  node.strokeAlign = 'INSIDE'
}

function bindRadius(node, token) {
  node.cornerRadius = TOKENS.radii[token] ? TOKENS.radii[token].Desktop : 0
  if (VARS.radius[token]) {
    try {
      node.setBoundVariable('topLeftRadius', VARS.radius[token])
      node.setBoundVariable('topRightRadius', VARS.radius[token])
      node.setBoundVariable('bottomLeftRadius', VARS.radius[token])
      node.setBoundVariable('bottomRightRadius', VARS.radius[token])
    } catch (e) {
      /* the plain value above already reads correctly */
    }
  }
}

async function label(text, family, weight, sizeToken, colourToken, tracking, upper) {
  const node = figma.createText()
  node.fontName = await font(TOKENS.families[family].family, weight)
  node.characters = upper ? text.toUpperCase() : text
  node.fontSize = TOKENS.sizes[sizeToken].Desktop
  if (VARS.size[sizeToken]) {
    try {
      node.setBoundVariable('fontSize', VARS.size[sizeToken])
    } catch (e) {
      /* value stands */
    }
  }
  if (tracking) node.letterSpacing = { unit: 'PERCENT', value: tracking * 100 }
  bindFill(node, colourToken)
  return node
}

/**
 * The pill. Every actionable thing on the site is one: a 1px ink outline, a
 * fill that carries the meaning, and an inverted state on hover. The fill and
 * the two sizes are variants, so a designer picks a button rather than drawing
 * one.
 */
async function buildButton() {
  const tones = [
    ['white', 'white', 'ink'],
    ['blue', 'blue', 'ink'],
    ['amber', 'amber', 'ink'],
    ['ink', 'ink', 'white'],
  ]
  const sizes = [['lg', 14, 30, 'small'], ['sm', 9, 22, 'micro']]

  const variants = []
  for (const tone of tones) {
    for (const size of sizes) {
      for (const state of ['default', 'hover']) {
        const frame = figma.createComponent()
        frame.name = 'Tone=' + tone[0] + ', Size=' + size[0] + ', State=' + state
        frame.layoutMode = 'HORIZONTAL'
        frame.primaryAxisSizingMode = 'AUTO'
        frame.counterAxisSizingMode = 'AUTO'
        frame.paddingTop = size[1]
        frame.paddingBottom = size[1]
        frame.paddingLeft = size[2]
        frame.paddingRight = size[2]
        frame.counterAxisAlignItems = 'CENTER'

        // On hover the pill inverts: the fill becomes the label's colour.
        const inverted = state === 'hover'
        bindFill(frame, inverted ? tone[2] : tone[1])
        bindStroke(frame, 'ink')
        bindRadius(frame, 'r-pill')

        const text = await label(
          'Button',
          'body',
          400,
          size[3],
          inverted ? tone[1] : tone[2],
          0.09,
          true,
        )
        frame.appendChild(text)
        variants.push(frame)
      }
    }
  }

  const set = figma.combineAsVariants(variants, figma.currentPage)
  set.name = 'Button'
  return set
}

/** A card: ink outline, card radius, a title and a line of copy. */
async function buildCard() {
  const variants = []
  for (const tone of ['white', 'blue', 'amber', 'purple']) {
    const frame = figma.createComponent()
    frame.name = 'Tone=' + tone
    frame.resize(360, 220)
    frame.layoutMode = 'VERTICAL'
    frame.primaryAxisSizingMode = 'FIXED'
    frame.counterAxisSizingMode = 'FIXED'
    frame.paddingTop = 28
    frame.paddingBottom = 28
    frame.paddingLeft = 28
    frame.paddingRight = 28
    frame.itemSpacing = 12
    bindFill(frame, tone)
    bindStroke(frame, 'ink')
    bindRadius(frame, 'r-card')

    const title = await label('Card title', 'display', 400, 'card-title', 'ink')
    const body = await label('One line of supporting copy.', 'body', 400, 'body-size', 'ink')
    frame.appendChild(title)
    frame.appendChild(body)
    // Only once it is inside the frame: a node has no layout sizing until it
    // has a parent that lays it out.
    body.layoutSizingHorizontal = 'FILL'
    variants.push(frame)
  }

  const set = figma.combineAsVariants(variants, figma.currentPage)
  set.name = 'Card'
  return set
}

/** The note beside a lesson: a label in the corner and a paragraph under it. */
async function buildCallout() {
  const frame = figma.createComponent()
  frame.name = 'Callout'
  frame.resize(680, 100)
  frame.layoutMode = 'VERTICAL'
  frame.primaryAxisSizingMode = 'AUTO'
  frame.counterAxisSizingMode = 'FIXED'
  frame.paddingTop = 20
  frame.paddingBottom = 20
  frame.paddingLeft = 24
  frame.paddingRight = 24
  frame.itemSpacing = 6
  bindFill(frame, 'blue')
  bindStroke(frame, 'ink')
  bindRadius(frame, 'r-editorial')

  const kind = await label('NOTE', 'mono', 400, 'micro', 'ink', 0.08, true)
  const body = await label('The note itself.', 'body', 400, 'body-size', 'ink')
  frame.appendChild(kind)
  frame.appendChild(body)
  body.layoutSizingHorizontal = 'FILL'
  return frame
}

/** The full-width row that carries you to the next session. */
async function buildPillRow() {
  const frame = figma.createComponent()
  frame.name = 'PillRow'
  frame.resize(1000, 92)
  frame.layoutMode = 'HORIZONTAL'
  frame.primaryAxisSizingMode = 'FIXED'
  frame.counterAxisSizingMode = 'FIXED'
  frame.counterAxisAlignItems = 'CENTER'
  frame.primaryAxisAlignItems = 'SPACE_BETWEEN'
  frame.paddingLeft = 32
  frame.paddingRight = 20
  bindFill(frame, 'white')
  bindStroke(frame, 'ink')
  bindRadius(frame, 'r-pill')

  const title = await label('Next session', 'display', 300, 'h3', 'ink')

  const arrow = figma.createFrame()
  arrow.name = 'Arrow'
  arrow.resize(44, 44)
  arrow.layoutMode = 'HORIZONTAL'
  arrow.primaryAxisAlignItems = 'CENTER'
  arrow.counterAxisAlignItems = 'CENTER'
  bindFill(arrow, 'white')
  bindStroke(arrow, 'ink')
  bindRadius(arrow, 'r-pill')
  const glyph = await label('→', 'body', 400, 'body-size', 'ink')
  arrow.appendChild(glyph)

  frame.appendChild(title)
  frame.appendChild(arrow)
  return frame
}

/** The trail above a page title. */
async function buildBreadcrumb() {
  const frame = figma.createComponent()
  frame.name = 'Breadcrumb'
  frame.layoutMode = 'HORIZONTAL'
  frame.primaryAxisSizingMode = 'AUTO'
  frame.counterAxisSizingMode = 'AUTO'
  frame.itemSpacing = 10
  frame.counterAxisAlignItems = 'CENTER'
  frame.fills = []

  const parts = ['Learn', '/', 'Foundation', '/', 'Session 1 of 5']
  for (const part of parts) {
    frame.appendChild(
      await label(part, 'mono', 400, 'micro', part === '/' ? 'purple' : 'grey-dark', 0.08, true),
    )
  }
  return frame
}

async function buildComponents() {
  say('Components…')

  const page = figma.currentPage
  const made = []
  made.push(await buildButton())
  made.push(await buildCard())
  made.push(await buildCallout())
  made.push(await buildPillRow())
  made.push(await buildBreadcrumb())

  // Laid out in a column on the canvas so the library reads as a sheet rather
  // than a pile at the origin.
  const board = figma.createFrame()
  board.name = 'Younit — components'
  board.layoutMode = 'VERTICAL'
  board.primaryAxisSizingMode = 'AUTO'
  board.counterAxisSizingMode = 'AUTO'
  board.itemSpacing = 64
  board.paddingTop = 64
  board.paddingBottom = 64
  board.paddingLeft = 64
  board.paddingRight = 64
  bindFill(board, 'grey')
  board.x = -1800
  board.y = 0
  page.appendChild(board)

  for (const node of made) board.appendChild(node)

  say(made.length + ' components')
  return board
}


/* ===== 30-page.js ===== */
/* --------------------------------------------------------------------------
   Snapshot → frames.

   The measurements come from a real browser, so this does not have to guess at
   layout. What it does add is the part a tracing tool cannot: where a fill
   matches a token it is bound to the variable, where a size matches the type
   scale it is bound to that, and where the page said "this is a button" the
   component is used instead of a rectangle with a word on it.
   -------------------------------------------------------------------------- */

let COMPONENTS = {}

/** The nearest type size token to a measured size, if it is close enough. */
function sizeTokenFor(size) {
  for (const name of Object.keys(TOKENS.sizes)) {
    if (Math.abs(TOKENS.sizes[name].Desktop - size) < 0.6) return name
  }
  return null
}

function radiusTokenFor(value) {
  for (const name of Object.keys(TOKENS.radii)) {
    if (Math.abs(TOKENS.radii[name].Desktop - value) < 0.6) return name
  }
  return null
}

function paintFor(rgba) {
  const token = tokenFor(rgba)
  const fill = {
    type: 'SOLID',
    color: { r: rgba.r, g: rgba.g, b: rgba.b },
    opacity: rgba.a === undefined ? 1 : rgba.a,
  }
  if (token && VARS.colour[token]) {
    return figma.variables.setBoundVariableForPaint(fill, 'color', VARS.colour[token])
  }
  return fill
}

const ALIGN = {
  'flex-start': 'MIN',
  start: 'MIN',
  center: 'CENTER',
  'flex-end': 'MAX',
  end: 'MAX',
  stretch: 'MIN',
  baseline: 'MIN',
  normal: 'MIN',
}

const JUSTIFY = {
  'flex-start': 'MIN',
  start: 'MIN',
  center: 'CENTER',
  'flex-end': 'MAX',
  end: 'MAX',
  'space-between': 'SPACE_BETWEEN',
  normal: 'MIN',
}

/** A text node carrying the words, the face and the colour it was measured in. */
async function buildText(node) {
  const text = figma.createText()
  const tx = node.tx
  text.fontName = await font(familyOf(tx.f), tx.w)
  text.characters = node.str
  text.name = node.n || 'text'

  text.fontSize = Math.max(1, tx.s)
  const token = sizeTokenFor(tx.s)
  if (token && VARS.size[token]) {
    try {
      text.setBoundVariable('fontSize', VARS.size[token])
    } catch (e) {
      /* the measured value already stands */
    }
  }

  if (tx.lh) text.lineHeight = { unit: 'PIXELS', value: tx.lh }
  if (tx.ls) text.letterSpacing = { unit: 'PIXELS', value: tx.ls }
  if (tx.c) text.fills = [paintFor(tx.c)]
  if (tx.u) text.textDecoration = 'UNDERLINE'
  if (tx.a === 'center') text.textAlignHorizontal = 'CENTER'
  else if (tx.a === 'right' || tx.a === 'end') text.textAlignHorizontal = 'RIGHT'
  else if (tx.a === 'justify') text.textAlignHorizontal = 'JUSTIFIED'

  // The box is the one the browser drew. Left to size itself the text would
  // rewrap, and every line below it in the page would move.
  text.textAutoResize = 'NONE'
  text.resize(Math.max(1, node.r[2]), Math.max(1, node.r[3]))
  return text
}

async function buildImage(node) {
  const rect = figma.createRectangle()
  rect.name = node.n || 'image'
  rect.resize(Math.max(1, node.r[2]), Math.max(1, node.r[3]))
  if (node.br) rect.cornerRadius = node.br[0]

  try {
    const image = await figma.createImageAsync(node.src)
    rect.fills = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: node.fit === 'contain' ? 'FIT' : 'FILL' }]
  } catch (e) {
    // A picture that will not load is drawn as the grey it sat on, named, so
    // the page still reads and the gap is obvious rather than invisible.
    rect.fills = [solid(hex(TOKENS.colours['grey-dark']), 0.25)]
    rect.name = 'missing image — ' + (node.n || node.src)
  }
  return rect
}

function buildVector(node) {
  try {
    const made = figma.createNodeFromSvg(node.svg)
    made.name = node.n || 'vector'
    made.resize(Math.max(1, node.r[2]), Math.max(1, node.r[3]))
    return made
  } catch (e) {
    return null
  }
}

/** An instance of the component this element is, sized as it was measured. */
function instanceFor(node) {
  const set = COMPONENTS[node.cmp]
  if (!set) return null
  try {
    const component = set.type === 'COMPONENT_SET' ? set.defaultVariant : set
    const instance = component.createInstance()
    // The component hugs its label; this one has to be the size the browser
    // drew, and a frame that hugs refuses to be resized until it is told to
    // stop.
    try {
      instance.primaryAxisSizingMode = 'FIXED'
      instance.counterAxisSizingMode = 'FIXED'
    } catch (e) {
      /* not an auto-layout component; it resizes freely */
    }
    instance.resize(Math.max(1, node.r[2]), Math.max(1, node.r[3]))
    return instance
  } catch (e) {
    return null
  }
}

async function buildNode(node, parentX, parentY) {
  if (node.t === 'T') {
    const text = await buildText(node)
    text.x = node.r[0] - parentX
    text.y = node.r[1] - parentY
    return text
  }

  if (node.t === 'I') {
    const image = await buildImage(node)
    image.x = node.r[0] - parentX
    image.y = node.r[1] - parentY
    return image
  }

  if (node.t === 'V') {
    const vector = buildVector(node)
    if (!vector) return null
    vector.x = node.r[0] - parentX
    vector.y = node.r[1] - parentY
    return vector
  }

  // A button is a button. Its words are inside it, so the children are not
  // rebuilt — the instance carries them.
  if (node.cmp === 'Button' || node.cmp === 'ArrowButton') {
    const instance = instanceFor(node)
    if (instance) {
      const words = firstText(node)
      if (words) {
        try {
          const target = instance.findOne((n) => n.type === 'TEXT')
          if (target) {
            await figma.loadFontAsync(target.fontName)
            target.characters = words
          }
        } catch (e) {
          /* the default label stays */
        }
      }
      instance.x = node.r[0] - parentX
      instance.y = node.r[1] - parentY
      return instance
    }
  }

  const frame = figma.createFrame()
  frame.name = node.n || 'frame'
  frame.resize(Math.max(1, node.r[2]), Math.max(1, node.r[3]))
  frame.x = node.r[0] - parentX
  frame.y = node.r[1] - parentY
  frame.fills = node.bg ? [paintFor(node.bg)] : []
  frame.clipsContent = node.clip === true

  if (node.bd) {
    frame.strokes = [paintFor(node.bd.c)]
    frame.strokeWeight = node.bd.w
    frame.strokeAlign = 'INSIDE'
  }

  if (node.br) {
    const token = radiusTokenFor(node.br[0])
    if (token && node.br[0] === node.br[1] && node.br[0] === node.br[2] && node.br[0] === node.br[3]) {
      bindRadius(frame, token)
    } else {
      frame.topLeftRadius = node.br[0]
      frame.topRightRadius = node.br[1]
      frame.bottomRightRadius = node.br[2]
      frame.bottomLeftRadius = node.br[3]
    }
  }

  if (node.op !== undefined) frame.opacity = node.op

  const children = node.ch || []
  for (const child of children) {
    const built = await buildNode(child, node.r[0], node.r[1])
    if (built) frame.appendChild(built)
  }

  // Auto layout last: the exporter has already checked that Figma would put
  // the children back where the browser had them, and setting it before they
  // are appended would move them on the way in.
  if (node.al && node.al.ok && frame.children.length) {
    const sizes = []
    for (const child of frame.children) sizes.push([child.width, child.height])

    frame.layoutMode = node.al.dir === 'V' ? 'VERTICAL' : 'HORIZONTAL'
    frame.primaryAxisSizingMode = 'FIXED'
    frame.counterAxisSizingMode = 'FIXED'
    frame.itemSpacing = Math.max(0, node.al.gap)
    frame.paddingTop = node.al.pad[0]
    frame.paddingRight = node.al.pad[1]
    frame.paddingBottom = node.al.pad[2]
    frame.paddingLeft = node.al.pad[3]
    frame.counterAxisAlignItems = ALIGN[node.al.align] || 'MIN'
    frame.primaryAxisAlignItems = JUSTIFY[node.al.justify] || 'MIN'

    // Auto layout resizes what it takes in; the measured sizes are the design.
    for (let i = 0; i < frame.children.length; i++) {
      const child = frame.children[i]
      try {
        child.layoutSizingHorizontal = 'FIXED'
        child.layoutSizingVertical = 'FIXED'
        child.resize(sizes[i][0], sizes[i][1])
      } catch (e) {
        /* a vector group cannot always be resized; it keeps its own size */
      }
    }
  }

  return frame
}

/** The first words inside a node, for labelling an instance. */
function firstText(node) {
  if (node.t === 'T') return node.str
  for (const child of node.ch || []) {
    const found = firstText(child)
    if (found) return found
  }
  return null
}

async function buildPage(snapshot, x, y) {
  const page = figma.createFrame()
  page.name = snapshot.route + '  ·  ' + snapshot.device + '  ·  ' + snapshot.locale
  page.resize(Math.max(1, snapshot.w), Math.max(1, Math.round(snapshot.h)))
  page.x = x
  page.y = y
  bindFill(page, 'grey')
  page.clipsContent = true
  figma.currentPage.appendChild(page)

  const tree = snapshot.tree
  if (tree) {
    for (const child of tree.ch || []) {
      const built = await buildNode(child, tree.r[0], tree.r[1])
      if (built) page.appendChild(built)
    }
    // A page whose whole body is one box still has to be drawn.
    if (!tree.ch || !tree.ch.length) {
      const built = await buildNode(tree, tree.r[0], tree.r[1])
      if (built) page.appendChild(built)
    }
  }

  return page
}


/* ===== 40-main.js ===== */
/* --------------------------------------------------------------------------
   The plugin itself: one button, and what happens behind it.

   The panel does the fetching — a Figma plugin's main thread has no network —
   and hands the JSON over. Everything else happens here.
   -------------------------------------------------------------------------- */

figma.showUI(__html__, { width: 380, height: 520, themeColors: true })

/** Components made this run, or found from a previous one. */
async function findComponents() {
  const found = {}
  const nodes = figma.currentPage.findAll(
    (n) => n.type === 'COMPONENT_SET' || n.type === 'COMPONENT',
  )
  for (const node of nodes) {
    if (node.parent && node.parent.type === 'COMPONENT_SET') continue
    found[node.name] = node
  }
  return found
}

async function runSystem() {
  await buildVariables()
  await buildPaintStyles()
  await buildTextStyles()
  const board = await buildComponents()
  COMPONENTS = await findComponents()
  return board
}

/** Variables have to exist before a page can be bound to them. */
async function ensureSystem() {
  if (Object.keys(VARS.colour).length) return
  await buildVariables()
  COMPONENTS = await findComponents()
}

figma.ui.onmessage = async (message) => {
  try {
    if (message.kind === 'base') {
      BASE = message.base
      return
    }

    if (message.kind === 'system') {
      const board = await runSystem()
      figma.viewport.scrollAndZoomIntoView([board])
      figma.ui.postMessage({ kind: 'done', message: 'Design system built.' })
      return
    }

    if (message.kind === 'pages') {
      await ensureSystem()
      COMPONENTS = await findComponents()

      const list = message.pages
      const made = []
      let x = 0
      let y = 0
      let tallest = 0

      for (let i = 0; i < list.length; i++) {
        const entry = list[i]
        step(i, list.length, entry.route + ' · ' + entry.device)

        const page = await buildPage(entry.snapshot, x, y)
        made.push(page)

        // Laid out in rows of five, each page a column of its own width, so a
        // hundred frames still read as a contact sheet rather than a stack.
        x += page.width + 160
        tallest = Math.max(tallest, page.height)
        if ((i + 1) % 5 === 0) {
          x = 0
          y += tallest + 200
          tallest = 0
        }
      }

      step(list.length, list.length, 'done')
      if (made.length) figma.viewport.scrollAndZoomIntoView(made)
      figma.ui.postMessage({
        kind: 'done',
        message: made.length + ' page' + (made.length === 1 ? '' : 's') + ' imported.',
      })
      return
    }

    if (message.kind === 'close') figma.closePlugin()
  } catch (error) {
    figma.ui.postMessage({ kind: 'error', message: String((error && error.message) || error) })
  }
}
